### ISSUE TITLE
OUTFIT shouldn't be a default liga

### ISSUE THREAD

**Issue by aaronbell** [Outfitio/Outfit-Fonts#2]
I note a `liga` of `sub o u t f i t by o_u_t_f_i_t;`. 

I suggest moving this to a stylistic set rather than a default ligature as it is unexpected as a default ligature (and may be undesirable to users).

**Comment by andyfitz** [comment]
Hey Aaron, This is considered a key attribute of the family and is also the typeface name. 
The horizontal footprint isnt drastically different from the non liga variation so we dont expect it to be an unwelcome feature when writing with it.
it's certainly the most extreme ligature in the set but ligatures remain an important characteristic.

**Comment by davelab6** [comment]
Can you show us the difference?

**Comment by aaronbell** [comment]
<img width="385" alt="Screen Shot 2021-08-18 at 4 41 43 PM" src="https://user-images.githubusercontent.com/8460297/129985800-1627b3af-9c38-4fec-8e3a-338e42333d19.png">

Here you go. Top is regular, bottom is ligated.

**Comment by davelab6** [comment]
I think it would be better if there were no metrics changes at all, just a mega ligated `utfit` - and that the actual logo, as shown, would be triggered by eg `outfit_logo_` or something much more unlikely to occur in regular text.

However, I am willing to accept this as-is if the opentype code is 'isolated,' so that it won't turn `outfitted' into `/outfit/t/e/d`, which I guess is currently the case.

@andyfitz would you be willing to go with my suggestion, or would you prefer just the 'isolated' code approach?

**Comment by andyfitz** [comment]
Hey @davelab6 outfit to tigger the liga was designed so that Outfit (capital O) would not via a utfit liga and look awkward.

Ideally we really do want this to remain as default behaviour when typing outfit standalone. 
The isolated approach would be acceptable (but we prefer the way it is now for aforementioned reasons)  

Hopefully using a typeface named 'outfit' this should not be unexpected.

I've reviewed outfitted and feel it's acceptable as ligature pairs are often in conflict with each other (rt vs tt etc)
Happy to take your call here mate - I think you look at one or two more typefaces than me ;-)

**Comment by davelab6** [comment]
I'm OK to just proceed. @aaronbell please PR

**Comment by RosaWagner** [comment]
Hi, @davelab6 can we reconsider this decision taking into consideration that this is not only a ligature, but also the brand logo of the company? I really think that a compromise should be found here.

<img width="101" alt="Capture d’écran 2021-09-29 à 12 57 27" src="https://user-images.githubusercontent.com/12222436/135255868-8317773d-1419-4188-bfd4-5886dd971cda.png">

**Comment by andyfitz** [comment]
> Hi, @davelab6 can we reconsider this decision taking into consideration that this is not only a ligature, but also the brand logo of the company? I really think that another compromise should be found here.
> 
> <img alt="Capture d’écran 2021-09-29 à 12 57 27" width="101" src="https://user-images.githubusercontent.com/12222436/135255868-8317773d-1419-4188-bfd4-5886dd971cda.png">

Hi @RosaWagner This same concern was true for Ubuntu and Red Hat (logotype being the typeface) yet they are hosted on Google fonts.

Also, currently this is not the logo of outfit, you'll notice the ascender's are different x-heights etc.

But to be clear, this  liga (including how words like outfitter and outfitted are displayed are a central attribute of this font's personality.  Not only will they not be removed the entire family wouldn't exist without them.

**Comment by RosaWagner** [comment]
> Also, currently this is not the logo of outfit, you'll notice the ascender's are different x-heights etc.

You can agree that the user won't notice such difference, this ligature is a very close variant of the logo :)

> This same concern was true for Ubuntu and Red Hat (logotype being the typeface) yet they are hosted on Google fonts.

I checked and, for what I see, the current version of the Red Hat fonts that GF is distributing is not containing such ligature (I don't even see a liga or a dlig feature). For Ubuntu, this font was onboarded in 2011, under a very special license (not OFL), and I am pretty sure that GF policy has evolved since. We can try to search for other OFL fonts doing a similar thing, but "outfit" is a very common word and ligatures are activated by default; user would share documents containing some kind of commercial communication without being aware of it. 

> But to be clear, this liga (including how words like outfitter and outfitted are displayed are a central attribute of this font's personality. Not only will they not be removed the entire family wouldn't exist without them.

I understand the aesthetic intention and the goal of identity :) Maybe you could consider again this good compromise mentioned by Aaron: a stylistic set or, eventually, a discretionary ligature? Or even having 2 versions of the fonts in this repo, like the Red Hat fonts?

Obviously I am not making the rules, and what I say here is binding only on me, not my employers. This is a valuable concern though, and I don't think we have a precedent for this one. Therefore, I would like another confirmation, to be sure that we considered all the consequences of this decision before guiding this font through the entire validation process.

**Comment by kenmcd** [comment]
This is just blatant advertising - which is why they do not want to make it optional.
The excuses are just that - silly excuses.
It is not a "font personality" - it is advertising.

Allowing an actual Outfit logo as an icon character makes more sense.
Allowing an actual Outfit logo a discretionary ligature also makes sense.
Why should there be a ligature for a common word which sorta looks like the logo?
It is advertising that they want users to accidentally-on-purpose run into.
Let's stop pretending.

Google Fonts should not be allowing blatant advertising into fonts they distribute.

**Comment by andyfitz** [comment]
I'll add that the ligatures for _outfitted_ and _outfitter_ contain the same liga aesthetic for continuity. 
All look great when you type them just as Red Hat Display looks good when you type Red Hat (also generic words that result in rendering 1:1 the logotype of a commercial entity)

**Comment by aaronbell** [comment]
To be clear, the reason why I posted this issue initially was not due to logo / marketing concerns, but one of user expectations and choice.

As a user, when I select a font and start using it in a project or document, I don't expect to see a random word (even if it is the font name) to be substituted with a ligature—it is an extremely uncommon default behavior. There isn't a special `courier` ligature in Courier, `times` ligature in Times New Roman or `Red Hat` ligature in Overpass. So this `outfit` replacement is very unusual.

Furthermore, as ligatures differ from standard text, they inherently draw attention to themselves. Even with the 'standard ligatures' such as `fl` and `fi`, the goal in their design is to avoid drawing too much attention to them as they need to disappear into the text flow. Still, they can be distracting and cause problems (like when text is tracked in / out). A book designer once told me that he sees decorative ligatures such as 'c_t', 's_t', etc. as if someone is talking with a lisp. I see `outfit` in a similar light—it draws too much attention to itself. 

Given the above, my biggest concern with the special ligature is that there's no easy way for users to opt out of it. A vast majority of users don't know how to turn on / off the `liga` opentype feature, and many applications don't even provide that functionality. So setting this ligature by default means that there will be a significant number of users who will be confused and frustrated by the appearance of the `outfit` ligature and won't know what to do about it.

I have zero concerns with the inclusion of this special ligated form in the font—many fonts include logos or stylistic variants. I simply feel that the decision to use it or not should be left to the user, who understands their needs and design intent best. As you said, this is a lovely font and it would be a shame for users to have to find another option because of this decision.

**Comment by andyfitz** [comment]
Thanks for clarifying your concern mate.
outfitted outfitter and outfit simply look better with the ligature by default rather than syncopated disconnected glyphs.

This may be a quirk to some (like all ligatures are : tt, fi etc) but won't invalidate the typeface for all users.  Perhaps even more words should become ligatures in future :)

**Comment by aaronbell** [comment]
I mean...in that case why don't you change the font design to connect all letters to all other letters? It'd be kind of like an upright connected script. Then you won't need special ligatures, and there's an expected cohesion for users. 😃

**Comment by andyfitz** [comment]
haha true,    but in this case it's designed to be a nice surprise.

Just like Baskerville Italic and it's graphical ampersand.   
Now if that were an alternate glyph, I would probably never have found my favourite ampersand.

I'm sure there are plenty who would have said it should follow the form of regular baskerville... but to me it's delightful

**Comment by andyfitz** [comment]
I think in future we could add more surprise liga words like:

fun
little
trim
title
tint

Would love ideas

**Comment by davelab6** [comment]
I approved the font to be added to GF as-is.
